In [25]:
import torch
import torch.nn as nn
from collections import OrderedDict
model = nn.Linear(2, 4, True)
np = model.named_parameters()

In [26]:
param_dict = {n:p for n,p in model.named_parameters()}
ordered_dict = OrderedDict(model.named_parameters())

In [27]:
for n, p in param_dict.items():
    print(n, p)

for n, p in ordered_dict.items():
    print(n, p)
    if ordered_dict[n].requires_grad:
        print ("this thing requires grad") 

weight Parameter containing:
tensor([[ 0.0586, -0.3458],
        [ 0.1746, -0.2399],
        [-0.5811, -0.3315],
        [ 0.0044, -0.3323]], requires_grad=True)
bias Parameter containing:
tensor([ 0.4326,  0.4987, -0.6775, -0.3716], requires_grad=True)
weight Parameter containing:
tensor([[ 0.0586, -0.3458],
        [ 0.1746, -0.2399],
        [-0.5811, -0.3315],
        [ 0.0044, -0.3323]], requires_grad=True)
this thing requires grad
bias Parameter containing:
tensor([ 0.4326,  0.4987, -0.6775, -0.3716], requires_grad=True)
this thing requires grad


In [28]:
@torch.no_grad()
def update_ema(ema_model, model, decay=0.9999):
    """
    Step the EMA model towards the current model.
    """
    
    # can use list comprehension alternative instead as well dict = {n:p for n,p in ...}
    ema_params = OrderedDict(ema_model.named_parameters())
    model_params = OrderedDict(model.named_parameters())

    for name, param in model_params.items():
        # p = 0.999 pold + 0.0001*pnew
        
        # apply only to params that require_grad to avoid small numerical changes in pos_embed
        # which should be registered as buffers either way
        if ema_params[name].requires_grad:
            ema_params[name].mul_(decay).add_(param.data, alpha = 1 - decay)

In [23]:
update_ema (model, model, decay=2)

In [29]:
model.weight


Parameter containing:
tensor([[ 0.0586, -0.3458],
        [ 0.1746, -0.2399],
        [-0.5811, -0.3315],
        [ 0.0044, -0.3323]], requires_grad=True)

In [8]:
with torch.no_grad():
    param_dict["weight"].add_(1, alpha=1)

In [9]:
param_dict["weight"]

Parameter containing:
tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]], requires_grad=True)

In [20]:
rank = False

master_process = True if rank else rank

In [21]:
master_process

False